import { pgTable, text, timestamp, boolean, integer, numeric, jsonb, doublePrecision } from 'drizzle-orm/pg-core';
import type {
  ServiceLocation,
  JobLabourItem,
  JobMaterialItem,
  JobExpenseItem,
  JobPhoto,
  JobDocument,
  JobSignature,
  JobChecklistItem,
  LineItem,
  FormField
} from '../types';

export const organizations = pgTable('organizations', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  address: text('address').notNull(),
  county: text('county').notNull(),
  country: text('country').notNull(),
  currency: text('currency').default('KES').notNull(),
  taxRate: doublePrecision('tax_rate').default(16.0).notNull(),
  eTimsEnabled: boolean('etims_enabled').default(true).notNull(),
  mpesaPaybill: text('mpesa_paybill'),
  mpesaTill: text('mpesa_till'),
  logo: text('logo'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull(),
  role: text('role').notNull(),
  avatar: text('avatar'),
  status: text('status').default('active').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const customers = pgTable('customers', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  type: text('type').default('individual').notNull(),
  name: text('name').notNull(),
  companyName: text('company_name'),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  address: text('address').notNull(),
  county: text('county').notNull(),
  area: text('area').notNull(),
  latitude: doublePrecision('latitude').notNull(),
  longitude: doublePrecision('longitude').notNull(),
  notes: text('notes').default(''),
  tags: jsonb('tags').$type<string[]>().default([]).notNull(),
  serviceLocations: jsonb('service_locations').$type<ServiceLocation[]>().default([]).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const technicians = pgTable('technicians', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  userId: text('user_id').notNull(),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  email: text('email').notNull(),
  specialization: text('specialization').notNull(),
  vehicleReg: text('vehicle_reg').notNull(),
  activeStatus: text('active_status').default('available').notNull(),
  currentLat: doublePrecision('current_lat').notNull(),
  currentLng: doublePrecision('current_lng').notNull(),
  currentLatitude: doublePrecision('current_latitude'),
  currentLongitude: doublePrecision('current_longitude'),
  lastLocationUpdate: text('last_location_update').notNull(),
  rating: doublePrecision('rating').default(5.0).notNull(),
  completedJobsCount: integer('completed_jobs_count').default(0),
  skills: jsonb('skills').$type<string[]>().default([]).notNull(),
  avatar: text('avatar'),
});

export const jobs = pgTable('jobs', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  jobNumber: text('job_number').notNull(),
  customerId: text('customer_id').notNull(),
  serviceLocationId: text('service_location_id'),
  title: text('title').notNull(),
  description: text('description').notNull(),
  priority: text('priority').default('medium').notNull(),
  status: text('status').default('new').notNull(),
  assignedTechnicianIds: jsonb('assigned_technician_ids').$type<string[]>().default([]).notNull(),
  scheduledDate: text('scheduled_date').notNull(),
  startTime: text('start_time').notNull(),
  endTime: text('end_time').notNull(),
  estimatedDurationMin: integer('estimated_duration_min'),
  estimatedDurationMinutes: integer('estimated_duration_minutes'),
  actualDurationMin: integer('actual_duration_min'),
  labour: jsonb('labour').$type<JobLabourItem[]>().default([]).notNull(),
  materials: jsonb('materials').$type<JobMaterialItem[]>().default([]).notNull(),
  expenses: jsonb('expenses').$type<JobExpenseItem[]>().default([]).notNull(),
  internalNotes: text('internal_notes'),
  customerNotes: text('customer_notes'),
  photos: jsonb('photos').$type<JobPhoto[]>().default([]).notNull(),
  documents: jsonb('documents').$type<JobDocument[]>().default([]).notNull(),
  customerSignature: jsonb('customer_signature').$type<JobSignature>(),
  checklist: jsonb('checklist').$type<JobChecklistItem[]>().default([]).notNull(),
  completionNotes: text('completion_notes'),
  travelStartTime: text('travel_start_time'),
  checkInTime: text('check_in_time'),
  checkOutTime: text('check_out_time'),
  checkInLat: doublePrecision('check_in_lat'),
  checkInLng: doublePrecision('check_in_lng'),
  invoiceId: text('invoice_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const estimates = pgTable('estimates', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  estimateNumber: text('estimate_number').notNull(),
  customerId: text('customer_id').notNull(),
  title: text('title'),
  status: text('status').default('draft').notNull(),
  date: text('date'),
  expiryDate: text('expiry_date').notNull(),
  items: jsonb('items').$type<LineItem[]>().default([]).notNull(),
  subtotal: doublePrecision('subtotal').default(0).notNull(),
  discountTotal: doublePrecision('discount_total'),
  taxRate: doublePrecision('tax_rate'),
  taxAmount: doublePrecision('tax_amount').default(0).notNull(),
  totalAmount: doublePrecision('total_amount').default(0).notNull(),
  notes: text('notes').default(''),
  terms: text('terms'),
  customerNotes: text('customer_notes'),
  approvedAt: text('approved_at'),
  convertedJobId: text('converted_job_id'),
  convertedInvoiceId: text('converted_invoice_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const invoices = pgTable('invoices', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  invoiceNumber: text('invoice_number').notNull(),
  customerId: text('customer_id').notNull(),
  jobId: text('job_id'),
  estimateId: text('estimate_id'),
  status: text('status').default('draft').notNull(),
  issueDate: text('issue_date'),
  dueDate: text('due_date').notNull(),
  items: jsonb('items').$type<LineItem[]>().default([]).notNull(),
  subtotal: doublePrecision('subtotal').default(0).notNull(),
  discountTotal: doublePrecision('discount_total'),
  taxRate: doublePrecision('tax_rate'),
  taxAmount: doublePrecision('tax_amount').default(0).notNull(),
  totalAmount: doublePrecision('total_amount').default(0).notNull(),
  depositAmount: doublePrecision('deposit_amount'),
  paidAmount: doublePrecision('paid_amount'),
  amountPaid: doublePrecision('amount_paid'),
  balanceDue: doublePrecision('balance_due').default(0).notNull(),
  notes: text('notes').default(''),
  terms: text('terms'),
  etimsControlCode: text('etims_control_code'),
  etimsCuSerialNumber: text('etims_cu_serial_number'),
  eTimsData: jsonb('etims_data').$type<{
    controlCode: string;
    qrData: string;
    cuSerialNumber: string;
    taxInvoiceType: string;
  }>(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const payments = pgTable('payments', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  invoiceId: text('invoice_id').notNull(),
  invoiceNumber: text('invoice_number'),
  customerId: text('customer_id'),
  amount: doublePrecision('amount').notNull(),
  paymentMethod: text('payment_method').notNull(),
  reference: text('reference').notNull(),
  phoneNumber: text('phone_number'),
  status: text('status').default('completed').notNull(),
  notes: text('notes'),
  paymentDate: text('payment_date'),
  receivedAt: text('received_at'),
  receivedBy: text('received_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  sku: text('sku').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  type: text('type').default('part'),
  category: text('category').notNull(),
  unit: text('unit').default('pcs'),
  costPrice: doublePrecision('cost_price').notNull(),
  sellingPrice: doublePrecision('selling_price').notNull(),
  stockQuantity: integer('stock_quantity').default(0).notNull(),
  minStockLevel: integer('min_stock_level').default(5).notNull(),
  warehouseId: text('warehouse_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const warehouses = pgTable('warehouses', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  name: text('name').notNull(),
  type: text('type').notNull(),
  technicianId: text('technician_id'),
  vehicleReg: text('vehicle_reg'),
  location: text('location').notNull(),
  isDefault: boolean('is_default').default(false).notNull(),
});

export const inventoryTransactions = pgTable('inventory_transactions', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  productId: text('product_id').notNull(),
  warehouseId: text('warehouse_id').notNull(),
  type: text('type').notNull(),
  quantity: integer('quantity').notNull(),
  unitCost: doublePrecision('unit_cost'),
  referenceType: text('reference_type'),
  referenceId: text('reference_id'),
  notes: text('notes'),
  performedByUserId: text('performed_by_user_id').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const customForms = pgTable('custom_forms', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  category: text('category').notNull(),
  version: integer('version').default(1).notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  requireSignature: boolean('require_signature').default(false).notNull(),
  fields: jsonb('fields').$type<FormField[]>().default([]).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const formSubmissions = pgTable('form_submissions', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  formId: text('form_id').notNull(),
  jobId: text('job_id'),
  technicianId: text('technician_id').notNull(),
  values: jsonb('values').notNull(),
  submittedAt: text('submitted_at').notNull(),
});

export const notifications = pgTable('notifications', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  userId: text('user_id').notNull(),
  type: text('type').notNull(),
  title: text('title').notNull(),
  message: text('message').notNull(),
  read: boolean('read').default(false).notNull(),
  link: text('link'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  orgId: text('org_id').notNull(),
  userId: text('user_id').notNull(),
  userName: text('user_name').notNull(),
  action: text('action').notNull(),
  entity: text('entity').notNull(),
  entityId: text('entity_id').notNull(),
  previousValue: text('previous_value'),
  newValue: text('new_value'),
  ipAddress: text('ip_address'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
